# Site settings
title: Twenty Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to the Kunji lab! Home of mitochondrial carrier research at the MRC-MBU in Cambridge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: mitocarriers
github_username:  ak2022

# Build settings
markdown: kramdown
